from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from uuid import UUID
from typing import Optional
from app.database import get_db
from app.models.product import Product
from app.schemas.product import ProductResponse, ProductCompareRequest, ProductCompareResponse

router = APIRouter(prefix="/api/products", tags=["products"])

@router.get("", response_model=list[ProductResponse])
async def list_products(
    brand: Optional[str] = None,
    min_price: Optional[float] = None,
    max_price: Optional[float] = None,
    source: Optional[str] = None,
    db: AsyncSession = Depends(get_db)
):
    stmt = select(Product)
    if brand: stmt = stmt.where(Product.brand.ilike(f"%{brand}%"))
    if min_price is not None: stmt = stmt.where(Product.price >= min_price)
    if max_price is not None: stmt = stmt.where(Product.price <= max_price)
    if source: stmt = stmt.where(Product.source == source)
    
    res = await db.execute(stmt)
    return [ProductResponse.model_validate(p) for p in res.scalars().all()]

@router.get("/{product_id}", response_model=ProductResponse)
async def get_product(product_id: UUID, db: AsyncSession = Depends(get_db)):
    res = await db.execute(select(Product).where(Product.id == product_id))
    p = res.scalar_one_or_none()
    if not p: raise HTTPException(status_code=404, detail="Product not found")
    return ProductResponse.model_validate(p)

@router.post("/compare", response_model=ProductCompareResponse)
async def compare_products(req: ProductCompareRequest, db: AsyncSession = Depends(get_db)):
    if len(req.product_ids) < 2 or len(req.product_ids) > 4:
        raise HTTPException(status_code=400, detail="Must provide 2-4 product IDs")
    
    stmt = select(Product).where(Product.id.in_(req.product_ids))
    res = await db.execute(stmt)
    products = res.scalars().all()
    
    if len(products) != len(req.product_ids):
        raise HTTPException(status_code=404, detail="One or more products not found")
        
    return ProductCompareResponse(
        products=[ProductResponse.model_validate(p) for p in products],
        comparison={"status": "Comparisons not generated by LLM yet"}
    )
